### ISSUE TITLE
파일 정보를 받아오는 함수인 stat함수를 조사했습니다.

### ISSUE THREAD

**Issue by mioky** [KIMSOOJIN97/Project2#11]
파일의 크기, 파일의 권한, 파일의 생성일시, 파일의 최종 변경일 등, 파일의 상태나 파일의 정보를 얻는 함수입니다. 
이 함수는 우리가 가장 많이 사용하는 명령어 중의 하나인 ls -al 명령어로 알 수 있는 내용들을 대부분 알 수 있습니다.

**Comment by mioky** [comment]
stat함수의 구조체 형태입니다.

struct stat { 
dev_t st_dev; /* ID of device containing file */
ino_t st_ino; /* inode number */ 
mode_t st_mode; /* 파일의 종류 및 접근권한 */ 
nlink_t st_nlink; /* hardlink 된 횟수 */ 
uid_t st_uid; /* 파일의 owner */ 
gid_t st_gid; /* group ID of owner */ 
dev_t st_rdev; /* device ID (if special file) */ 
off_t st_size; /* 파일의 크기(bytes) */ 
blksize_t st_blksize; /* blocksize for file system I/O */ 
blkcnt_t st_blocks; /* number of 512B blocks allocated */ 
time_t st_atime; /* time of last access */ 
time_t st_mtime; /* time of last modification */ 
time_t st_ctime; /* time of last status change */ };

**Comment by taehunpb** [comment]
ㅎ

**Comment by taehunpb** [comment]
수고 했어...요

**Comment by soooojinn** [comment]
대단해요
