### ISSUE TITLE
파일의 시간 정보를 가져오는 함수 작성했습니다.

### ISSUE THREAD

**Issue by mioky** [KIMSOOJIN97/Project2#12]
파일의 정보를 가져오기 위해 stat함수와 localtime함수를 사용했습니다.

**Comment by mioky** [comment]
localtime함수에 대해 조사했습니다.

헤더 time.h
형태 struct tm *localtime(const time_t *t);
인수time_t *t  //시간 time_t 값
반환 struct tm *  //시간에 대한 struct tm 값의 포인터

**Comment by taehunpb** [comment]
수고 했어요..

**Comment by soooojinn** [comment]
수고했습니당
