### ISSUE TITLE
localtime() 함수조사

### ISSUE THREAD

**Issue by taehunpb** [KIMSOOJIN97/Project2#15]
Syntax
The syntax for the localtime function in the C Language is:

struct tm *localtime(const time_t *timer);
Parameters or Arguments
timer
A pointer to an object of type time_t that contains a time value to convert.
Returns
The localtime function returns a pointer to a structure broken-down local time equivalent describing a calendar time pointed to by timer.

Required Header
In the C Language, the required header for the localtime function is:

#include <time.h>

ref https://www.techonthenet.com/c_language/standard_library_functions/time_h/localtime.php

**Comment by mioky** [comment]
오오 Good
