### ISSUE TITLE
struct tm *location 구조체 포인터 변수

### ISSUE THREAD

**Issue by taehunpb** [KIMSOOJIN97/Project2#19]
struct tm* localtime : 시간 정보가 포함된 구조체 포인터 변수이다.

이 중 시간 비교를 위해 필요한 변수는 아래의 시간, 분, 초 관련 변수이다.

int tm_sec; /* seconds */
int tm_min; /* minutes */
int tm_hour; /* hours */

**Comment by mioky** [comment]
훌륭합니다!!!
