### ISSUE TITLE
두 개의 파일 사이즈를 비교

### ISSUE THREAD

**Issue by soooojinn** [KIMSOOJIN97/Project2#20]
stat 함수를 사용하여 파일의 정보를 받아서 각각의 파일에 대한 사이즈 정보를 받아왔습니다.
이를 기반으로 text1,text2 파일의 사이즈를 비교하였습니다.

**Comment by taehunpb** [comment]
수고..했어요..

**Comment by mioky** [comment]
수고했습니다!!
